spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama2

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    com.example.aichatbot: DEBUG 