spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  ai:
    ollama:
      base-url: http://localhost:11434
      model: llama3.1
      embeddings:
        model: llama3.1
    openai:
      api-key: ${OPENAI_API_KEY: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}
      model: gpt-3.5-turbo
      temperature: 0.7
      max-tokens: 1000
      base-url: https://api.openai.com/v1
    qdrant:
      url: localhost
      port: 6334
      collection-name: documents
      dimension: 384
      similarity: cosine
      score-threshold: 0.7
      top-k: 5

server:
  port: 8080

logging:
  level:
    org.springframework.ai: DEBUG
    com.example.aichatbot: DEBUG 
